version: '3.8'

services:
  kafka-training:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka-training
    ports:
      - "39092:39092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:39092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-training:29092,EXTERNAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-training:29093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "my-training-cluster-id"
    volumes:
      - kafka-training-data:/var/lib/kafka/data
    networks:
      - kafka_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-training-ui
    depends_on:
      - kafka-training
    ports:
      - "8099:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: training
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-training:29092
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge

volumes:
  kafka-training-data:
